#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation

hello_the_world:
    path: /
    defaults: { _controller: 'App\Controller\HelloController:hello' }
